language: python

python:
  - "3.6"
  - "3.8"
  - "pypy3"

install:
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - coverage run --source=textparser setup.py test
  - make test-sdist
  - env PYTHONPATH=. python examples/hello_world.py
  - env PYTHONPATH=. python examples/benchmarks/json/errors.py
  - env PYTHONPATH=. python examples/benchmarks/json/parse_tree.py
  - env PYTHONPATH=. python examples/json.py
  - env PYTHONPATH=. python examples/benchmarks/json/speed.py

after_success:
  coveralls
